spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 1234
    url: jdbc:mysql://localhost:3306/spring_boot_cloud_training
    username: root
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
